remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: GFM
title: Build, Govern, and Scale AI Solutions
description: A hands-on Team Week experience with Cowork and Scout.
